stages:
- name: Build
  steps:
    - runScriptConfig:
        image: maven:3.6.0-jdk-8-alpine
        shellScript: mvn -B -U -DskipTests clean package spring-boot:repackage

- name: Publish
  steps:
    - publishImageConfig:
        dockerfilePath: ./eureka_server/Dockerfile
        tag: 192.168.66.101:8889/test/eureka_service
        pushRemote: true
        registry: http://192.168.66.101:8889

    - publishImageConfig:
        dockerfilePath: ./config_server/Dockerfile
        tag: 192.168.66.101:8889/test/config_service
        pushRemote: true
        registry:  http://192.168.66.101:8889

    - publishImageConfig:
        dockerfilePath: ./zuul_server/Dockerfile
        tag: 192.168.66.101:8889/test/zuul_service
        pushRemote: true
        registry:  http://192.168.66.101:8889

    - publishImageConfig:
        dockerfilePath: ./service_user/Dockerfile
        tag: 192.168.66.101:8889/test/service_user
        pushRemote: true
        registry:  http://192.168.66.101:8889

    - publishImageConfig:
        dockerfilePath: ./service_product/Dockerfile
        tag: 192.168.66.101:8889/test/service_product
        pushRemote: true
        registry:  http://192.168.66.101:8889

    - publishImageConfig:
        dockerfilePath: ./service_product/Dockerfile
        tag: 192.168.66.101:8889/test/service_product
        pushRemote: true
        registry:  http://192.168.66.101:8889

- name: Deploy
  steps:
    - applyYamlConfig:
        path: ./Deployment.yaml

notification: {}