eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/            # 指定注册中心

server:
  port: 10020   # 服务自己的访问端口


spring:
  application:
    name: service-product   # 服务名，
  # 数据库配置（数据库：fa_microservice_product）
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/fa_microservice_product?useUnicode=true&characterEncoding=utf-8&useSSL=true&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

# 配置日志级别
logging:
  level:
    root: info


